import { useMemo } from 'react';

import { IEmail } from 'src/types/emails';

// ----------------------------------------------------------------------

const EMAILS: IEmail[] = [
  {
    id: '1',
    email: 'ava@outreachmagic.co',
    host: 'outreachmagic',
    server: 'google personal',
    inboxPlacement: false,
    inboxEngagement: true,
    placementAccount: false,
    engagementAccount: false,
    inboxReset: false,
    relayAccount: false,
    vpsName: 'Windows VPS',
    smtp: true,
    imap: false,
    status: 'Disabled',
  },
  {
    id: '2',
    email: 'hailey@outreachmagic.co',
    host: 'outreachmagic',
    server: 'google personal',
    inboxPlacement: false,
    inboxEngagement: true,
    placementAccount: false,
    engagementAccount: false,
    inboxReset: false,
    relayAccount: false,
    vpsName: 'Windows VPS',
    smtp: true,
    imap: true,
    status: 'Disabled',
  },
  {
    id: '3',
    email: 'ava@outreachmagic.net',
    host: 'outreachmagic',
    server: 'microsoft business',
    inboxPlacement: false,
    inboxEngagement: true,
    placementAccount: false,
    engagementAccount: false,
    inboxReset: false,
    relayAccount: false,
    vpsName: 'Windows VPS',
    smtp: true,
    imap: false,
    status: 'Disabled',
  },
  {
    id: '4',
    email: 'hailey@outreachmagic.net',
    host: 'outreachmagic',
    server: 'google personal',
    inboxPlacement: false,
    inboxEngagement: true,
    placementAccount: false,
    engagementAccount: false,
    inboxReset: false,
    relayAccount: false,
    vpsName: 'Windows VPS',
    smtp: true,
    imap: true,
    status: 'Disabled',
  },
  {
    id: '5',
    email: 'ava@magicoutreach.co',
    host: 'outreachmagic',
    server: 'google personal',
    inboxPlacement: false,
    inboxEngagement: true,
    placementAccount: false,
    engagementAccount: false,
    inboxReset: false,
    relayAccount: false,
    vpsName: 'Windows VPS',
    smtp: false,
    imap: true,
    status: 'Disabled',
  },
  {
    id: '6',
    email: 'hailey@magicoutreach.co',
    host: 'outreachmagic',
    server: 'microsoft business',
    inboxPlacement: false,
    inboxEngagement: true,
    placementAccount: false,
    engagementAccount: false,
    inboxReset: false,
    relayAccount: false,
    vpsName: 'Windows VPS',
    smtp: false,
    imap: true,
    status: 'Disabled',
  },
  {
    id: '7',
    email: 'john@k2renewleads.com',
    host: 'k2renewleads',
    server: 'microsoft business',
    inboxPlacement: true,
    inboxEngagement: false,
    placementAccount: true,
    engagementAccount: false,
    inboxReset: true,
    relayAccount: true,
    vpsName: 'Windows VPS',
    smtp: true,
    imap: true,
    status: 'Active',
  },
];

export function useGetEmails() {
  const memoizedValue = useMemo(
    () => ({
      seeds: EMAILS,
      seedsLoading: false,
      seedsError: false,
      seedsValidating: false,
      seedsEmpty: !EMAILS.length,
    }),
    []
  );

  return memoizedValue;
}
